name = "[1.21] TEDS Plus"
author = "DovydasTEDS"
version = "2.16.0+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d45371453e916e0def1f6ca0080085683d4c64d26a10387b5b238fe478acd1cb"

[versions]
fabric = "0.16.14"
minecraft = "1.21"
