name = "TEDS Plus"
author = "DovydasTEDS"
version = "2.16.1+1.21.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7080a11e72ce2ffc91b596e7fd8d1f84727dc633283753a2491e7e3960ff74a6"

[versions]
fabric = "0.16.14"
minecraft = "1.21"
