name = "[1.21.4] TEDS Plus"
author = "DovydasTEDS"
version = "2.16.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c050c4d1464ed5310dd17dcf55558995885625f7cc355fb702dc0ae28e989a6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
