name = "TEDS Plus"
author = "DovydasTEDS"
version = "2.16.1+1.21.7.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd07adf20739cb281164f934b243a3936c0a476ac128df0bbcb19377b18f9055"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.4", "1.21.5"]
