name = "[1.21.1] TEDS Plus"
author = "DovydasTEDS"
version = ""
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f2d078f77ba9d26516a5a39293852b8c30778520aef611ddcd98f5a9c98b966"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
