name = "[1.21.5] TEDS Plus"
author = "DovydasTEDS"
version = ""
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "426983731c485d3e7b7f6430fafb60e498fc79850b9a19f27394cd87adfe315a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.4", "1.21.5"]
