name = "TEDS Plus"
author = "DovydasTEDS"
version = "2.16.1+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31233b9b33105bebc7c7c5bb04ca3ad9dfff898372dfdd431430948246d53c5e"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.4", "1.21.5"]
